### PR TITLE
updated react

### PR DESCRIPTION
**Pull request by rblakeley**
updated to stable version of React

### CODE REVIEW

**Comment by ZuzanaBenicko** [comment]
Hello,

I am trying to implement your great weather component to Reapp project but I am having this error:

Uncaught TypeError: Can't add property context, object is not extensible
Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.
warning.js:36 Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory
warning.js:36 Warning: Don't set the props property of the component. Mutate the existing props object instead.

I was searching for it and it looks like it might be a problem with various versions of React.
Please don't you know how would I fix this? 
Thanks!

**Comment by rblakeley** [comment]
It's working fine for me. It's probably your syntax that's just a bit off. It would help if you shared some code, either here or as a question on StackOverflow.

**Comment by ZuzanaBenicko** [comment]
Hello,
trying to do as simple as I can (yes in case of question, I installed your forecast through npm before using it), thanks I will paste it here, and if you do not know I'll try StackOverflow. Thanks again! :)

import { Reapp, Button, View } from 'reapp-kit';
import React from 'react'
import Forecast from 'react-forecast'

export default class Test extends React.Component 
{
    render() 
    {
        return  (
         <Forecast latitude={34.05} longitude={118.25} name={'Los Angeles'} />
       );
    };
}

Maybe it is because of Reapp, really do not know.

**Comment by cezary** [comment]
I hadn't published the latest updates to npm; the old published version was still using react 0.12.0. Can you try reinstalling?

**Comment by ZuzanaBenicko** [comment]
Great! it helped! 

Thank you a lot! :) have a great day!

**Comment by ZuzanaBenicko** [comment]
And one note :) in usage you say for changing units we should manage prop 'units'....but it is 'unit'. :) just for those who do not know why it is not working

**Pull request merged**
